//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public class Task extends com.zeroc.Ice.Value
{
    public Task()
    {
        this.funct = "";
    }

    public Task(String funct, double lowerLimit, double upperLimit, int approach)
    {
        this.funct = funct;
        this.lowerLimit = lowerLimit;
        this.upperLimit = upperLimit;
        this.approach = approach;
    }

    public String funct;

    public double lowerLimit;

    public double upperLimit;

    public int approach;

    public Task clone()
    {
        return (Task)super.clone();
    }

    public static String ice_staticId()
    {
        return "::Demo::Task";
    }

    @Override
    public String ice_id()
    {
        return ice_staticId();
    }

    /** @hidden */
    public static final long serialVersionUID = 2114978178L;

    /** @hidden */
    @Override
    protected void _iceWriteImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice(ice_staticId(), -1, true);
        ostr_.writeString(funct);
        ostr_.writeDouble(lowerLimit);
        ostr_.writeDouble(upperLimit);
        ostr_.writeInt(approach);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _iceReadImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        funct = istr_.readString();
        lowerLimit = istr_.readDouble();
        upperLimit = istr_.readDouble();
        approach = istr_.readInt();
        istr_.endSlice();
    }
}
